using System.IO;

namespace OpenNEL.Utils;

public static class MimeTypes
{
    public static string Get(string path)
    {
        var ext = Path.GetExtension(path).ToLowerInvariant();
        if (ext == ".html") return "text/html";
        if (ext == ".xhtml") return "application/xhtml+xml";
        if (ext == ".htm") return "text/html";
        if (ext == ".shtml") return "text/html";
        if (ext == ".css") return "text/css";
        if (ext == ".js") return "application/javascript";
        if (ext == ".mjs") return "application/javascript";
        if (ext == ".cjs") return "application/javascript";
        if (ext == ".jsx") return "application/javascript";
        if (ext == ".ts") return "application/typescript";
        if (ext == ".tsx") return "application/typescript";
        if (ext == ".mts" || ext == ".cts") return "application/typescript";
        if (ext == ".json") return "application/json";
        if (ext == ".map") return "application/json";
        if (ext == ".ndjson") return "application/x-ndjson";
        if (ext == ".rss") return "application/rss+xml";
        if (ext == ".atom") return "application/atom+xml";
        if (ext == ".xml") return "application/xml";
        if (ext == ".txt") return "text/plain";
        if (ext == ".log") return "text/plain";
        if (ext == ".md") return "text/markdown";
        if (ext == ".toml") return "application/toml";
        if (ext == ".yaml" || ext == ".yml") return "application/x-yaml";
        if (ext == ".tsv") return "text/tab-separated-values";
        if (ext == ".xsd") return "application/xml";
        if (ext == ".xsl" || ext == ".xslt") return "application/xml";
        if (ext == ".plist") return "application/x-plist";
        if (ext == ".lock") return "text/plain";
        if (ext == ".config") return "text/plain";
        if (ext == ".png") return "image/png";
        if (ext == ".jpg" || ext == ".jpeg") return "image/jpeg";
        if (ext == ".gif") return "image/gif";
        if (ext == ".bmp") return "image/bmp";
        if (ext == ".tif" || ext == ".tiff") return "image/tiff";
        if (ext == ".webp") return "image/webp";
        if (ext == ".avif") return "image/avif";
        if (ext == ".svg") return "image/svg+xml";
        if (ext == ".svgz") return "image/svg+xml";
        if (ext == ".ico") return "image/x-icon";
        if (ext == ".cur") return "image/x-icon";
        if (ext == ".epub") return "application/epub+zip";
        if (ext == ".woff") return "font/woff";
        if (ext == ".woff2") return "font/woff2";
        if (ext == ".ttf") return "font/ttf";
        if (ext == ".otf") return "font/otf";
        if (ext == ".eot") return "application/vnd.ms-fontobject";
        if (ext == ".csv") return "text/csv";
        if (ext == ".pdf") return "application/pdf";
        if (ext == ".zip") return "application/zip";
        if (ext == ".gz") return "application/gzip";
        if (ext == ".tar") return "application/x-tar";
        if (ext == ".7z") return "application/x-7z-compressed";
        if (ext == ".rar") return "application/vnd.rar";
        if (ext == ".iso") return "application/x-iso9660-image";
        if (ext == ".wasm") return "application/wasm";
        if (ext == ".mp4") return "video/mp4";
        if (ext == ".webm") return "video/webm";
        if (ext == ".ogv") return "video/ogg";
        if (ext == ".mpeg" || ext == ".mpg") return "video/mpeg";
        if (ext == ".m2ts" || ext == ".mts") return "video/mp2t";
        if (ext == ".asf") return "video/x-ms-asf";
        if (ext == ".avi") return "video/x-msvideo";
        if (ext == ".mkv") return "video/x-matroska";
        if (ext == ".mov") return "video/quicktime";
        if (ext == ".flv") return "video/x-flv";
        if (ext == ".3gp") return "video/3gpp";
        if (ext == ".m3u8") return "application/vnd.apple.mpegurl";
        if (ext == ".wmv") return "video/x-ms-wmv";
        if (ext == ".mp3") return "audio/mpeg";
        if (ext == ".ogg") return "audio/ogg";
        if (ext == ".wav") return "audio/wav";
        if (ext == ".m4a") return "audio/mp4";
        if (ext == ".aac") return "audio/aac";
        if (ext == ".opus") return "audio/opus";
        if (ext == ".mid" || ext == ".midi") return "audio/midi";
        if (ext == ".flac") return "audio/flac";
        if (ext == ".amr") return "audio/amr";
        if (ext == ".srt") return "application/x-subrip";
        if (ext == ".rtf") return "application/rtf";
        if (ext == ".doc") return "application/msword";
        if (ext == ".docx") return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        if (ext == ".xls") return "application/vnd.ms-excel";
        if (ext == ".xlsx") return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        if (ext == ".ppt") return "application/vnd.ms-powerpoint";
        if (ext == ".pptx") return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        if (ext == ".apk") return "application/vnd.android.package-archive";
        if (ext == ".aab") return "application/x-aab";
        if (ext == ".msi") return "application/x-msi";
        if (ext == ".appx" || ext == ".msix" || ext == ".msixbundle") return "application/vnd.ms-appx";
        if (ext == ".exe") return "application/x-msdownload";
        if (ext == ".psd") return "image/vnd.adobe.photoshop";
        if (ext == ".ps" || ext == ".eps" || ext == ".ai") return "application/postscript";
        if (ext == ".heic") return "image/heic";
        if (ext == ".heif") return "image/heif";
        if (ext == ".properties") return "text/plain";
        if (ext == ".conf" || ext == ".ini") return "text/plain";
        if (ext == ".less" || ext == ".sass" || ext == ".scss") return "text/css";
        if (ext == ".webmanifest") return "application/manifest+json";
        if (ext == ".manifest") return "text/cache-manifest";
        if (ext == ".ics") return "text/calendar";
        if (ext == ".kml") return "application/vnd.google-earth.kml+xml";
        if (ext == ".kmz") return "application/vnd.google-earth.kmz";
        if (ext == ".jar") return "application/java-archive";
        if (ext == ".war" || ext == ".ear") return "application/java-archive";
        if (ext == ".class") return "application/java-vm";
        if (ext == ".deb") return "application/x-deb";
        if (ext == ".rpm") return "application/x-rpm";
        if (ext == ".dmg") return "application/x-apple-diskimage";
        if (ext == ".cab") return "application/vnd.ms-cab-compressed";
        if (ext == ".xz") return "application/x-xz";
        if (ext == ".bz") return "application/x-bzip";
        if (ext == ".bz2") return "application/x-bzip2";
        if (ext == ".zst") return "application/zstd";
        if (ext == ".cbor") return "application/cbor";
        if (ext == ".sqlite" || ext == ".db") return "application/x-sqlite3";
        if (ext == ".swf") return "application/x-shockwave-flash";
        if (ext == ".torrent") return "application/x-bittorrent";
        if (ext == ".eml") return "message/rfc822";
        if (ext == ".aif" || ext == ".aiff") return "audio/aiff";
        if (ext == ".oga") return "audio/ogg";
        if (ext == ".mka") return "audio/x-matroska";
        if (ext == ".weba") return "audio/webm";
        if (ext == ".m3u") return "audio/mpegurl";
        if (ext == ".mpd") return "application/dash+xml";
        if (ext == ".icns") return "image/icns";
        if (ext == ".jp2") return "image/jp2";
        if (ext == ".jxl") return "image/jxl";
        if (ext == ".apng") return "image/apng";
        if (ext == ".pem" || ext == ".cer" || ext == ".crt" || ext == ".der") return "application/x-x509-ca-cert";
        if (ext == ".p12" || ext == ".pfx") return "application/x-pkcs12";
        if (ext == ".key" || ext == ".pub") return "application/octet-stream";
        if (ext == ".graphql") return "application/graphql";
        if (ext == ".bat" || ext == ".cmd" || ext == ".ps1") return "text/plain";
        if (ext == ".sh") return "application/x-sh";
        if (ext == ".glb") return "model/gltf-binary";
        if (ext == ".gltf") return "model/gltf+json";
        if (ext == ".stl") return "model/stl";
        if (ext == ".dae") return "model/vnd.collada+xml";
        if (ext == ".obj") return "model/obj";
        if (ext == ".3mf") return "model/3mf";
        if (ext == ".vert" || ext == ".frag" || ext == ".glsl") return "text/plain";
        if (ext == ".py" || ext == ".java" || ext == ".c" || ext == ".cpp" || ext == ".h" || ext == ".hpp" || ext == ".go" || ext == ".rs" || ext == ".cs" || ext == ".swift" || ext == ".kt" || ext == ".m" || ext == ".mm") return "text/plain";
        if (ext == ".xps") return "application/vnd.ms-xpsdocument";
        if (ext == ".mdx") return "text/markdown";
        if (ext == ".vue" || ext == ".svelte") return "text/plain";
        if (ext == ".json5") return "application/json";
        if (ext == ".hjson") return "application/hjson";
        if (ext == ".markdown") return "text/markdown";
        if (ext == ".sqlite3") return "application/x-sqlite3";
        if (ext == ".parquet") return "application/x-parquet";
        if (ext == ".avro") return "application/avro";
        if (ext == ".ipa") return "application/octet-stream";
        if (ext == ".nupkg" || ext == ".vsix") return "application/octet-stream";
        if (ext == ".crx") return "application/x-chrome-extension";
        if (ext == ".rst") return "text/x-rst";
        if (ext == ".tex") return "text/x-tex";
        if (ext == ".opf") return "application/oebps-package+xml";
        if (ext == ".npmrc" || ext == ".yarnrc" || ext == ".editorconfig") return "text/plain";
        if (ext == ".babelrc") return "application/json";
        return "application/octet-stream";
    }
}
